services:
  autoheal:
    image: willfarrell/autoheal:1.1.0
    container_name: ah
    mem_limit: 128m
    cpus: 0.5
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: 2
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=5
      - AUTOHEAL_START_PERIOD=30
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
      - DOCKER_SOCK=tcp://ds:2375
