location /transmission/
{
    proxy_intercept_errors off;

    client_max_body_size 0;
    add_header Front-End-Https on;
    add_header Accept-Ranges bytes;

    proxy_redirect off;
    proxy_set_header Host $http_host;
    proxy_set_header X-NginX-Proxy true;
    proxy_set_header Connection "upgrade";
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_pass_header X-Transmission-Session-Id;

     location /transmission/rpc 
     {
          proxy_pass http://tr/transmission/rpc;
     }

    proxy_pass http://tr/transmission/;
}

location /transmission/share
{
    alias /webroot/hako/Transmission;

    client_max_body_size 100m;
    add_header Accept-Ranges bytes;    
    client_body_temp_path /webroot/davtmp;
    create_full_put_path on;

    autoindex on;
    autoindex_exact_size off;
    autoindex_localtime on;
    dav_methods PUT DELETE MKCOL COPY MOVE;
    dav_access user:rw group:rw all:rw;
    allow all;
}
