location ^~ /gr/
{
    proxy_hide_header Content-Security-Policy;
    add_header Content-Security-Policy "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:" always;
    proxy_intercept_errors off;
    proxy_pass https://raw.githubusercontent.com/;
    proxy_set_header Host "raw.githubusercontent.com";
}