location ^~ /nichan/
{
    proxy_hide_header Content-Security-Policy;
    add_header Content-Security-Policy "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:" always;
    proxy_intercept_errors off;

    location ~ ^/nira/.+/binary-cache-url$
    {
        add_header Content-Type text/plain;
        return 200 "https://$host/nica";
    }

    set $upstream_endpoint https://channels.nixos.org;

    proxy_pass "https://channels.nixos.org/";
    proxy_set_header Host "channels.nixos.org";
    proxy_ssl_server_name on;
    proxy_redirect "https://channels.nixos.org/" /nichan/;
    proxy_redirect "https://releases.nixos.org/" /nira/;
    proxy_redirect "https://cache.nixos.org/" /nica/;

    proxy_cache nix_ch;
}

location ^~ /nica/
{
    proxy_hide_header Content-Security-Policy;
    add_header Content-Security-Policy "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:" always;
    proxy_intercept_errors off;
    set $upstream_endpoint https://cache.nixos.org;

    proxy_pass "https://cache.nixos.org/";
    proxy_set_header Host "cache.nixos.org";
    proxy_ssl_server_name on;
    proxy_redirect "https://channels.nixos.org/" /nichan/;
    proxy_redirect "https://releases.nixos.org/" /nira/;
    proxy_redirect "https://cache.nixos.org/" /nica/;

    proxy_cache nix_bc;
}

location ^~ /nira/
{
    proxy_hide_header Content-Security-Policy;
    add_header Content-Security-Policy "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:" always;
    location ~ ^/nira/.+/binary-cache-url$
    {
        add_header Content-Type text/plain;
        return 200 "https://$host/nica";
    }

    proxy_intercept_errors off;
    set $upstream_endpoint //releases.nixos.org;

    proxy_pass "https://releases.nixos.org/";
    proxy_set_header Host "releases.nixos.org";
    proxy_redirect "https://channels.nixos.org/" /nichan/;
    proxy_redirect "https://releases.nixos.org/" /nira/;
    proxy_redirect "https://cache.nixos.org/" /nica/;

    proxy_cache nix_rel;
}