proxy_cache_path /var/cache/nginx/nix_ch levels=1:2 keys_zone=nix_ch:100m max_size=10g inactive=365d use_temp_path=off;
proxy_cache_path /var/cache/nginx/nix_bc levels=1:2 keys_zone=nix_bc:100m max_size=10g inactive=365d use_temp_path=off;
proxy_cache_path /var/cache/nginx/nix_rel levels=1:2 keys_zone=nix_rel:100m max_size=10g inactive=365d use_temp_path=off;
