server 
{
    listen 80;
     server_name blc.*;
    location / { return 301 https://$host$request_uri; }
}

server
{
    listen 443 ssl;
    server_name blc.*;

    include /etc/nginx/conf.d/locations/000-home.conf;

    location /
    {        
        location ~ ^/(index.html|custom_public)
        {
            add_header Cache-Control no-cache;
            proxy_pass http://lc;
        }

        location = /api/chat
        {
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_pass http://lc;
        }
    
        proxy_pass http://lc;
    }
}
